# can also be a list
inputloc : ['/dampe/data3/users/public/crawler/txt/*.txt']
outputdir: /dampe/data3/XROOTD_DIR/MC/reco/v5r4p2
DMPSWSYS: /cvmfs/dampe.cern.ch/rhel6-64/opt/releases/DmpSoftware-5-4-2
tag: v5r4p2
workdir:   /tmp/zimmers/repro/
files_per_job : 100
max_jobs : 100
time_per_job  : 2:00:00
mem_per_job   : 4G
sleep_cycle   : 12:00:00
